services:
  kokomen-nest-server-prod:
    build:
      context: ../../
      dockerfile: ./apps/kokomen-server/Dockerfile
    container_name: kokomen-nest-server-prod
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      TZ: Asia/Seoul
      NODE_ENV: production
      DATABASE_HOST: ${DATABASE_HOST_PROD}
      DATABASE_PORT: 3306
      DATABASE_USERNAME: ${DATABASE_USERNAME_PROD}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD_PROD}
      DATABASE_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD_PROD}
      DATABASE_DATABASE: kokomen
      REDIS_HOST: ${REDIS_HOST_PROD}
      REDIS_PORT: 6379
      PORT: 3000
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ap-northeast-2
      AWS_BEDROCK_RESUME_EVALUATION_FLOW_ID: ${AWS_BEDROCK_RESUME_EVALUATION_FLOW_ID}
      AWS_BEDROCK_RESUME_EVALUATION_FLOW_ALIAS_ID: ${AWS_BEDROCK_RESUME_EVALUATION_FLOW_ALIAS_ID}
    restart: on-failure:3

  nginx:
    image: nginx:alpine
    container_name: kokomen-nest-nginx-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../../apps/kokomen-server/nginx/prod/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - kokomen-nest-server-prod
    restart: unless-stopped
    environment:
      TZ: Asia/Seoul
