version: "3.8"

services:
  client:
    image: ${DOCKER_USERNAME}/kokomen-client:development
    container_name: kokomen-client
    expose:
      - "3000"
    restart: always
    networks:
      - dev-kokomen-net

  nginx:
    image: nginx:latest
    container_name: kokomen-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot
    depends_on:
      - client
    restart: always
    networks:
      - dev-kokomen-net
networks:
  dev-kokomen-net:
    external: true
    driver: bridge
