name: Deployment Nestjs server (Prod)

on:
  push:
    branches: [main-disabled-temporarily]

jobs:
  build-and-deploy:
    name: Build and Deploy to EC2
    runs-on: [self-hosted, ocr]

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: install dependencies
        run: |
          sudo corepack enable
          sudo yarn install

      - name: Run Docker Compose on ${{ matrix.server }}
        env:
          DATABASE_HOST_PROD: ${{ secrets.DATABASE_HOST_PROD }}
          DATABASE_USERNAME_PROD: ${{ secrets.DATABASE_USERNAME_PROD }}
          DATABASE_PASSWORD_PROD: ${{ secrets.DATABASE_PASSWORD_PROD }}
          DATABASE_ROOT_PASSWORD_PROD: ${{ secrets.DATABASE_ROOT_PASSWORD_PROD }}
          REDIS_HOST_PROD: ${{ secrets.REDIS_HOST_PROD }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_BEDROCK_RESUME_EVALUATION_FLOW_ID: ${{ secrets.AWS_BEDROCK_RESUME_EVALUATION_FLOW_ID }}
          AWS_BEDROCK_RESUME_EVALUATION_FLOW_ALIAS_ID: ${{ secrets.AWS_BEDROCK_RESUME_EVALUATION_FLOW_ALIAS_ID }}
        run: |
          cd /home/ubuntu
          sudo chmod 666 /var/run/docker.sock 
          cd /home/ubuntu/actions-runner/_work/kokomen-client/kokomen-client
          yarn types:build
          docker system prune -f
          docker compose -f ./docker/server/compose.prod.yaml down || true
          docker compose -f ./docker/server/compose.prod.yaml up -d --build
